
my $engrish_dictionary = {
    ' help' => ' herupu',
    ' you' => ' yuu',                           # TODO: maybe change it to 'me'?  kudquote: "May I help me?"
    ' let\'s' => " lettsu",
        ' programming' => ' puroguramingu',     # previously: 'programming' => 'purogrammingu',
        ' sup' => ' hauu ar yuu and a-imu fine sankyuu',
        ' do' => ' can',
        ' thank' => ' sankyuu',
        ' rescue' => ' resukyuu',
        ' see' => ' shee',
        ' holy' => ' horii',
        ' holiday' => ' horiday',
        ' much' => ' macchi',
        ' hi' => ' guddo mo-ningu- and habu a naisu daai',
        ' the' => ' thaa',                      # TODO: da? daa? thaa?
        ' get' => ' getto',
        ' up' => '  appu',
        ' morning' => ' moruningu',
        ' cockroach' => ' kokuroacchi',
        ' hnnnghh' => ' doki doki...do...---...',
        ' power' => ' powaa',
        ' who' => ' hu-',
        ' it\'s' => ' ittsu',
        ' right' => ' raito',
        ' I\'ve' => ' a-ibu',                   # TODO: plural and remaining singular count distinctions
        ' hello' => ' wafuu',
        ' good' => ' guddo',
        ' nice' => ' naisu',
        ' day' => ' daai',
        ' time' => ' taimuu',
        ' am' => ' amu',
        '\.' => ' nano desu',
        '\,' => ' ..etoo..',
        '\?' => '!?',
        ' terrible' => ' teriburu',
        ' accident' => ' akushindento',
         ' while' => ' meanwhile I\'m poorly proportioned, short, stupid, bad at English, don\'t have any breasts, act like sich a kid and',            # quoted
    ' dog' => ' Strelka',
    ' ok' => ' I\'ll just try to imagine what you said and nod a lot',
    ' protip' => ' purofesshionaru adubaissu',
    ' friend' => ' furiendo',
    ' need' => 'needo',
    ' indeed' => 'indeedo',
    # TODO: we need moar entries
    };
